version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8096:8096"
    volumes:
      - ./config/jellyfin:/config
      - ./media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://localhost:8096

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - ./config/sonarr:/config
      - ./downloads:/downloads

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - ./config/radarr:/config
      - ./downloads:/downloads

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    ports:
      - "6767:6767"
    volumes:
      - ./config/bazarr:/config
      - ./downloads:/downloads

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    volumes:
      - /var/lib/tailscale:/var/lib/tailscale
