version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - film_volume:/film
      - ./config/jellyfin:/config
    ports:
      - "8096:8096"

  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    volumes:
      - film_volume:/film
      - ./config/aria2:/config
    environment:
      - RPC_SECRET=${RPC_SECRET} #Ambil dari github secrets
    ports:
      - "6800:6800"

  rclone:
    image: rclone/rclone
    container_name: rclone
    volumes:
      - film_volume:/film
      - ./config/rclone:/config
    command: sync remote:path /film --config /config/rclone.conf

  kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./config/kuma:/app/data
    ports:
      - "3001:3001"

  bot:
    build: .
    container_name: telegram-bot
    volumes:
      - ./config:/config
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} #mbil dari github secrets
      - FLY_API_TOKEN=${FLY_API_TOKEN}
    command: python3 /app/bot/bot.py

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - "8080:8080"
    volumes:
      - film_volume:/film
      - ./config/qbittorrent:/config
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - film_volume:/srv
      - ./config/filebrowser:/config
    ports:
      - "8081:80"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    volumes:
      - ./config/organizr:/config
    ports:
      - "8888:80"
    restart: unless-stopped

  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - "19999:19999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  film_volume:
