version: '3.8'

services:
  bioskop-jellyfin:
    image: jellyfin/jellyfin
    container_name: bioskop-jellyfin
    volumes:
      - ./config/jellyfin:/config
      - /film:/film
    ports:
      - "8096:8096"

  bioskop-aria2:
    image: p3terx/aria2-pro
    container_name: bioskop-aria2
    volumes:
      - ./config/aria2:/config
      - /film:/film
    ports:
      - "6800:6800"

  bioskop-qbittorrent:
    image: linuxserver/qbittorrent
    container_name: bioskop-qbittorrent
    volumes:
      - ./config/qbittorrent:/config
      - /film:/downloads
    ports:
      - "6881:6881"
      - "6881:6881/udp"

  bioskop-uptime-kuma:
    image: louislam/uptime-kuma
    container_name: bioskop-uptime-kuma
    volumes:
      - ./config/kuma:/app/data
    ports:
      - "3001:3001"

  bioskop-filebrowser:
    image: filebrowser/filebrowser
    container_name: bioskop-filebrowser
    volumes:
      - /film:/srv
    ports:
      - "8080:80"

  bioskop-prowlarr:
    image: linuxserver/prowlarr
    container_name: bioskop-prowlarr
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"

  bioskop-organizr:
    image: organizr/organizr
    container_name: bioskop-organizr
    volumes:
      - ./config/organizr:/config
    ports:
      - "80:80"

  bioskop-netdata:
    image: netdata/netdata
    container_name: bioskop-netdata
    ports:
      - "19999:19999"
