app = "jellyfin-rclone"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "film_volume"
  destination = "/film"

[env]
  JELLYFIN_DATA_DIR = "/config/jellyfin"
  ARIA2_DOWNLOAD_DIR = "/film"
  RCLONE_CONFIG_DIR = "/config/rclone"

[services]
  [[services.ports]]
    internal_port = 8096
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    internal_port = 3001
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    internal_port = 8080
    handlers = ["http"]

  [[services.ports]]
    internal_port = 8081
    handlers = ["http"]

  [[services.ports]]
    internal_port = 9696
    handlers = ["http"]

  [[services.ports]]
    internal_port = 8888
    handlers = ["http"]

  [[services.ports]]
    internal_port = 19999
    handlers = ["http"]
