# fly.toml
app = "bioskop"
primary_region = "sin"

[build]
  image = "bioskop:latest"

[env]
  FLY_API_TOKEN = "{{ .Env.FLY_API_TOKEN }}"
  TELEGRAM_BOT_TOKEN = "{{ .Env.TELEGRAM_BOT_TOKEN }}"
  RPC_SECRET = "{{ .Env.RPC_SECRET }}"
  SONARR_API_KEY = "{{ .Env.SONARR_API_KEY }}"
  RADARR_API_KEY = "{{ .Env.RADARR_API_KEY }}"
  BAZARR_API_KEY = "{{ .Env.BAZARR_API_KEY }}"
  QBITTORRENT_USERNAME = "{{ .Env.QBITTORRENT_USERNAME }}"
  QBITTORRENT_PASSWORD = "{{ .Env.QBITTORRENT_PASSWORD }}"
  TAILSCALE_AUTHKEY = "{{ .Env.TAILSCALE_AUTHKEY }}"
  FLY_VOLUME_ID = "{{ .Env.FLY_VOLUME_ID }}"

[mounts]
  source = "media"
  destination = "/media"
