app = "bioskop"  # Ganti dengan nama aplikasi Fly.io

primary_region = "sin"

[build]
  image = "registry.fly.io/bioskop:latest"

[mounts]
  source = "film_volume"
  destination = "/film"
  
[deploy]
  strategy = "immediate"


[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 8080
    handlers = ["http"]

  [[services.ports]]
    port = 6880  # Aria2 RPC/WebUI

  [[services.ports]]
    port = 3000  # Uptime Kuma

  [[services.ports]]
    port = 8920  # Jellyfin HTTPS

  [[services.ports]]
    port = 7359  # Jellyfin auto-discovery

  [[services.ports]]
    port = 1900  # Jellyfin DLNA

  [[services.ports]]
    port = 5000  # API atau lainnya

  [[services.ports]]
    port = 9090  # Monitoring

[[checks]]
  type = "http"
  port = 8080
  interval = "10s"
  timeout = "2s"
