app = "bioskop"
primary_region = "sin"

[build]
  image = "registry.fly.io/bioskop:latest"

[deploy]
  strategy = "immediate"

[env]
  FLY_APP_NAME = "bioskop"

[[services]]
  protocol = "tcp"
  internal_port = 80
  auto_start_machines = true
  auto_stop_machines = false
